version: '3'

services:
  app:
    build: .
    container_name: app-db-connection-test
    ports:
      - "80:80"
    networks:
      - default
      - interdocker
    restart: unless-stopped

networks:
  default:
    driver: bridge
  interdocker:
    external: true