version: '3'

services:
  app:
    build: .
    container_name: app-database-connection
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx_conf:/etc/nginx/conf.d
      - ./docker/php.ini:/etc/php/8.0/fpm/php.ini
    networks:
      - default
      - interdocker
    restart: unless-stopped

networks:
  default:
    driver: bridge
  interdocker:
    external: true